export interface ClipDefinition {
  id: number;
  title: string;
  features: string[];
  preState: string[];
  recordingSteps: string[];
  postState: string[];
  enabled: boolean;
  outputPath?: string;
}

export const clips: ClipDefinition[] = [
  {
    id: 1,
    title: "Create New Apps",
    features: ["New App dialog", "9-step scaffolding", "Auto port allocation"],
    preState: [
      "Dashboard open and maximized on DP-1",
      "Dashboard showing Apps view (nav-apps)",
      "No apps named taskManager or weatherApp exist",
      "Right monitor (HDMI-1) is clear/unused",
    ],
    recordingSteps: [
      "Click 'New App' button in dashboard",
      "NewAppDialog — fill name: taskManager, description: Task management application",
      "Click 'Create' — new tab opens showing create-app flow",
      "Wait for all 9 steps to complete (scaffold, git, GitHub, ports, worktree, systemd, deps, build, start)",
      "Navigate back to Apps view",
      "Click 'New App' again",
      "Fill name: weatherApp, description: Weather dashboard application",
      "Click 'Create' — wait for completion",
      "Show Apps view with both new apps listed",
    ],
    postState: [
      "taskManager and weatherApp apps exist and are running",
      "Dashboard showing Apps view with both apps visible",
      "Two create-app tabs may still be open",
    ],
    enabled: true,
    outputPath: "/opt/automateLinux/data/clip1-create-new-apps.mp4",
  },
  {
    id: 2,
    title: "Create Issues",
    features: ["Issue creation", "Multi-app issues", "Label assignment"],
    preState: [
      "taskManager and weatherApp apps exist (from Clip 1)",
      "Dashboard open on left monitor",
      "Both apps have 0 issues",
    ],
    recordingSteps: [
      "Navigate to Issues view (nav-issues)",
      "Find taskManager card — click '+ New' (new-issue)",
      "Create issue: 'Login form validation missing for email field' / label: bug",
      "Create issue: 'Add dark mode toggle to settings page' / label: feature",
      "Create issue: 'API rate limiting not enforced on public endpoints' / labels: bug, not-urgent",
      "Find weatherApp card — click '+ New'",
      "Create issue: 'Temperature display shows Kelvin instead of Celsius' / label: bug",
      "Create issue: 'Search results pagination broken on page 2' / label: bug",
      "Create issue: 'Add 5-day forecast widget to homepage' / label: feature",
      "Show Issues view with both apps and their issues",
      "Show sidebar badges updating (open count)",
    ],
    postState: [
      "taskManager has 3 open issues (#1, #2, #3)",
      "weatherApp has 3 open issues (#1, #2, #3)",
      "Dashboard showing Issues view with both apps' issues visible",
      "Sidebar shows total open count badge",
    ],
    enabled: false,
  },
  {
    id: 3,
    title: "Issue Detail & Context Menu",
    features: ["Detail panel", "Action buttons", "Context menu", "Note conversion"],
    preState: [
      "Both apps have issues (from Clip 2)",
      "Dashboard showing Issues view",
    ],
    recordingSteps: [
      "Click on taskManager issue #1 title — detail slide-out panel opens",
      "Show: issue number, status badge, description, labels, timestamps",
      "Pause 4s on detail panel",
      "Close panel (Escape)",
      "Hover over issue #2 — show action buttons (copy, edit, close/reopen, delete)",
      "Click edit — edit dialog opens — change description — save",
      "Click copy — copies 'taskManager#2: Add dark mode toggle' to clipboard",
      "Right-click issue #3 — context menu appears",
      "Show options: View details, Focus terminal, Toggle urgent, Convert to/from note, Mark not in progress",
      "Click 'Convert to note' — issue #3 gets sticky-note icon",
      "Right-click again — click 'Convert from note' to revert",
      "Right-click — click 'Toggle urgent' — not-urgent label toggled",
    ],
    postState: [
      "Issue #2 has slightly updated description",
      "Issue #3 may have toggled labels",
      "Dashboard showing Issues view, detail panel closed",
    ],
    enabled: false,
  },
  {
    id: 4,
    title: "Issue Lifecycle & Labels",
    features: ["Status transitions", "Terminal + Dashboard", "Label management"],
    preState: [
      "Both apps have issues (from Clips 2-3)",
      "Dashboard showing Issues view on left monitor",
      "Terminal open on right monitor (HDMI-1)",
    ],
    recordingSteps: [
      "Terminal: d listIssues --app taskManager — show issue list",
      "d updateIssue --app taskManager --issueNumber 1 --status in_progress",
      "Dashboard: Issue #1 turns purple + spinning loader — pause 4s",
      "d updateIssue --app taskManager --issueNumber 1 --status review",
      "Dashboard: issue #1 turns blue + eye icon — pause 4s",
      "d closeIssue --app taskManager --issueNumber 1 --insights 'Fixed email validation with regex'",
      "Dashboard: issue #1 gets strikethrough + faded — pause 4s",
      "d reopenIssue --app taskManager --issueNumber 1",
      "Dashboard: issue #1 returns to open — pause 3s",
      "d closeIssue --app taskManager --issueNumber 1",
      "Right-click closed issue #1 — 'Fix regression with Claude' — shows regression state — pause 4s",
      "Show sidebar badges updating (in-progress purple, review blue, regression red)",
      "Show note label behavior: note issues skip lifecycle",
      "Show not-urgent label: yellow warning styling",
    ],
    postState: [
      "taskManager issue #1: closed (or regression)",
      "Issues #2, #3: still open",
      "weatherApp issues: unchanged (all open)",
      "Dashboard + terminal both visible",
    ],
    enabled: false,
  },
  {
    id: 5,
    title: "Fix with Claude — Dialog",
    features: ["Fix with Claude dialog", "Plan/Team/Tmux modes", "Scheduling", "Command preview"],
    preState: [
      "Both apps have issues with various states (from Clip 4)",
      "Dashboard showing Issues view",
    ],
    recordingSteps: [
      "Select taskManager issue #2 checkbox — 'Fix with Claude' button activates",
      "Click 'Fix with Claude' — Launch dialog opens",
      "Show auto-generated prompt referencing issue #2",
      "Pause 4s on prompt",
      "Cancel dialog",
      "Select BOTH issues #2 and #3 — button shows 'Fix 2'",
      "Click 'Fix 2 with Claude' — dialog shows multi-issue prompt",
      "Pause 4s",
      "Toggle Plan Mode ON — amber highlight",
      "Toggle Team Mode ON — blue highlight",
      "Toggle Tmux ON — green highlight",
      "Pause 3s — all 3 toggles lit",
      "Click 'After delay' schedule — show delay input",
      "Click 'At time' schedule — show datetime picker",
      "Switch back to 'Now'",
      "Expand 'Command preview' — show full bash command",
      "Pause 4s on command preview",
      "Click copy button on command preview",
      "Cancel dialog",
    ],
    postState: [
      "No issues launched — dialog was cancelled",
      "Dashboard showing Issues view, no state changes",
    ],
    enabled: false,
  },
  {
    id: 6,
    title: "Launch Claude & Session Tracking",
    features: ["Claude launch", "Tmux integration", "Session tracking", "Hook events"],
    preState: [
      "taskManager issue #2 ('Add dark mode toggle') is open",
      "Dashboard on left, terminal on right",
      "No active Claude sessions (clean slate preferred)",
    ],
    recordingSteps: [
      "Select taskManager issue #2 — click 'Fix with Claude'",
      "Enable Tmux toggle",
      "Click 'Launch'",
      "Dashboard: Issue #2 immediately turns purple (in_progress)",
      "Terminal: Claude session launches in tmux — show real terminal output",
      "Let Claude work for 1-2 minutes",
      "Navigate to Claude sessions tab (nav-claude)",
      "Show active session card: title, elapsed timer, last hook event badge, associated issue",
      "Expand hook events panel — show events streaming in with colors",
      "Switch back to Issues view — show issue #2 still purple",
      "If Claude finishes: issue moves to review (blue) automatically",
      "Show commit being created with format '#2: Add dark mode toggle'",
    ],
    postState: [
      "taskManager issue #2: in_progress or review",
      "Active or recently completed Claude session exists",
      "Session ID linked to issue #2",
      "Terminal on right shows Claude session",
    ],
    enabled: false,
  },
  {
    id: 7,
    title: "Claude Sessions Tab Deep Dive",
    features: ["Session cards", "Hook event colors", "Title editing", "Reorder"],
    preState: [
      "At least one Claude session exists (from Clip 6)",
      "Dashboard on left monitor",
    ],
    recordingSteps: [
      "Navigate to Claude tab (nav-claude)",
      "Show session list with the session from Clip 6",
      "Show session card: editable title, elapsed timer (live), last hook event",
      "Click to edit session title — type new name — save",
      "Expand hook events panel",
      "Show color-coded events: Yellow=PreToolUse, Green=PostToolUse, Red=Failure, Blue=Session, Cyan=UserPrompt, Purple=Subagent, Amber=Permission, Orange=Notification",
      "Show associated issue badge with workflow state color",
      "Show sidebar Claude badge with hook count",
      "If multiple sessions: show drag-to-reorder",
    ],
    postState: [
      "Dashboard showing Claude sessions tab",
      "Session title may have been renamed",
    ],
    enabled: false,
  },
  {
    id: 8,
    title: "Session Resume & History",
    features: ["Resume sessions", "Session picker", "Session lineage"],
    preState: [
      "Issue #2 has at least one completed session (from Clip 6)",
      "Dashboard showing Issues view or Claude tab",
    ],
    recordingSteps: [
      "Navigate to Issues view",
      "Find taskManager issue #2 (should be review or closed)",
      "Show 'Resume' button on the issue",
      "Left-click Resume — new terminal opens with claude -r <sessionId>",
      "Terminal: Show Claude resuming with previous context",
      "Let it run briefly",
      "Stop/exit the resumed session",
      "Right-click Resume (if multiple sessions) — show session picker menu",
      "Show issue's claudeSessionIds containing multiple session IDs",
      "Show session lineage (resumedFrom field) in session details",
    ],
    postState: [
      "Issue #2 has 2+ session IDs",
      "Additional Claude session created (now closed)",
    ],
    enabled: false,
  },
  {
    id: 9,
    title: "Scheduled Launches",
    features: ["Delayed scheduling", "Countdown timer", "Auto-launch"],
    preState: [
      "weatherApp has open issues (from Clip 2)",
      "Dashboard showing Issues view",
    ],
    recordingSteps: [
      "Select weatherApp issue #1",
      "Click 'Fix with Claude'",
      "Click 'After delay' — set to 1 minute",
      "Click 'Schedule'",
      "Dashboard: issue shows orange background + clock icon + countdown timer",
      "Show countdown ticking (useScheduledIssues polls every 3s)",
      "Wait for countdown to reach zero",
      "Session auto-launches — terminal appears on right",
      "Issue transitions to purple (in_progress)",
      "Cancel/stop the session after brief demo",
    ],
    postState: [
      "weatherApp issue #1: in_progress",
      "New Claude session active",
    ],
    enabled: false,
  },
  {
    id: 10,
    title: "Hooks System",
    features: ["Hook events", "Auto-approval", "Permission prompts", "Notifications"],
    preState: [
      "Active Claude session exists (from Clip 9 or new)",
      "Dashboard on left showing Claude tab or Issues view",
    ],
    recordingSteps: [
      "Show active session's hook events streaming in real-time",
      "Point out: SessionStart event (blue), PreToolUse events (yellow), PostToolUse (green)",
      "Show notify-dashboard.sh forwarding events to dashboard API",
      "Show safe-bash-commands.sh auto-approving a safe command (ls, git status)",
      "Show a permission prompt for an unsafe/blocked command",
      "Show PostToolUseFailure (red) if one occurs",
      "Show NotificationRequest triggering attention counter",
      "Show sidebar hook count badges updating",
      "Show SubagentStart (purple) if agent team is active",
    ],
    postState: [
      "Dashboard showing hook events",
      "Session still active or completed",
    ],
    enabled: false,
  },
  {
    id: 11,
    title: "MCP Server & Daemon Tools",
    features: ["MCP tools", "Daemon commands", "Screenshot", "Input simulation"],
    preState: [
      "Terminal open on right monitor",
      "Dashboard on left (any view)",
    ],
    recordingSteps: [
      "Terminal: Show Claude Code session",
      "Claude uses daemon_screenshot — takes screenshot",
      "Claude uses daemon_list_ports — shows port registry",
      "Claude uses daemon_app_status — shows all app statuses",
      "Claude uses daemon_mouse_click — clicks something on screen",
      "Claude uses daemon_send_command — sends arbitrary command",
      "Show the MCP tool list in Claude's available tools",
      "Show the daemon responding to each command",
      "Show the UDS socket path: /run/automatelinux/automatelinux-daemon.sock",
    ],
    postState: [
      "Terminal showing Claude with MCP tool output",
    ],
    enabled: false,
  },
  {
    id: 12,
    title: "Desktop Automation",
    features: ["Mouse control", "Keyboard control", "Drag & drop", "Multi-monitor"],
    preState: [
      "Dashboard on left, terminal on right",
      "Desktop visible (some windows may need to be minimized)",
    ],
    recordingSteps: [
      "daemon_screenshot — show dual-monitor composite with cursor overlay",
      "daemon_mouse_move — move cursor across screen smoothly",
      "daemon_mouse_click — click a UI element",
      "daemon_keyboard_type — type text into focused field",
      "daemon_keyboard_key — press Enter, Escape",
      "daemon_mouse_drag — drag a window",
      "Show GNOME Activities: keyboardType works there (simulateInput doesn't)",
      "Show coordinate translation between monitors (HDMI-1 y-offset: 159px)",
      "Show MutterSession: Mutter RemoteDesktop API for mouse, ydotool for keyboard",
    ],
    postState: [
      "Desktop may have rearranged windows",
      "Demonstration of each automation capability shown",
    ],
    enabled: false,
  },
  {
    id: 13,
    title: "Multi-Peer Network",
    features: ["Peer cards", "Remote execution", "Auto-forwarding"],
    preState: [
      "Dashboard on left, terminal on right",
      "Peers tab accessible",
    ],
    recordingSteps: [
      "Click 'Peers' in sidebar (nav-peers)",
      "Show peer cards: leader (online), desktop (online), others (offline)",
      "Show each card: hostname, IP, MAC, daemon version, version delta, deploy button",
      "Terminal: d listPeers — show peer list",
      "d getPeerInfo --peer leader — show leader details",
      "d execOnPeer --peer leader --directory /opt/automateLinux --shellCmd 'uptime' — remote execution",
      "Show result returning",
      "d execOnPeer --peer leader --directory /opt/automateLinux --shellCmd 'd listPorts' — daemon command on remote",
      "Show: worker forwarding (commands auto-forward to leader when needed)",
    ],
    postState: [
      "Dashboard showing Peers tab",
      "Terminal showing peer command outputs",
    ],
    enabled: false,
  },
  {
    id: 14,
    title: "GNOME Clock Extension",
    features: ["Clock widget", "Session count", "Context menu", "Drag position"],
    preState: [
      "At least one Claude session active or recent",
      "Desktop visible",
      "Clock extension running",
    ],
    recordingSteps: [
      "Show desktop — clock widget at top-left: 'HH:MM' + '(N)' session count",
      "Move mouse to clock to highlight it",
      "Right-click — context menu with active Claude sessions (color-coded)",
      "Click a session entry — associated terminal window activates",
      "Drag clock to new position (e.g., top-right corner)",
      "Show position persistence (saved to daemon clockX/clockY)",
      "Show attention counter updating when session has Stop/Notification events",
      "Show fallback: if dashboard unavailable, still shows process count via pgrep",
    ],
    postState: [
      "Clock may have moved to new position",
      "Terminal window activated from session click",
    ],
    enabled: false,
  },
  {
    id: 15,
    title: "Permission System & Auto-Approval",
    features: ["Safe command whitelist", "Shell operator blocking", "Permission prompts"],
    preState: [
      "Claude Code session running in terminal (right monitor)",
      "Dashboard on left (any view)",
    ],
    recordingSteps: [
      "Claude runs ls — auto-approved (settings.json whitelist)",
      "Claude runs git status — auto-approved (safe-bash-commands.sh)",
      "Claude runs a command with shell operators — blocked (security)",
      "Claude runs command with $() — permission prompt shown",
      "Show testClaudePermissions function output",
      "Show settings.json allowed patterns (63+ entries)",
      "Show safe-bash-commands.sh logic: strip quotes — check operators — whitelist match",
      "Show git commit using git commit -F - <<'EOF' pattern (no $() wrapper)",
    ],
    postState: [
      "Terminal showing permission examples",
    ],
    enabled: false,
  },
  {
    id: 16,
    title: "Git Sync & Issue Storage",
    features: ["JSON file storage", "Auto git commits", "CRUD tracking"],
    preState: [
      "Issues exist in taskManager and weatherApp (from previous clips)",
      "Terminal on right, dashboard on left",
    ],
    recordingSteps: [
      "Terminal: ls /opt/issues/ — show per-app directories",
      "ls /opt/issues/taskManager/ — show JSON files per issue",
      "cat /opt/issues/taskManager/1.json — show issue data as JSON",
      "d createIssue --app taskManager --title 'Test git sync'",
      "cd /opt/issues && git log -3 — show commit: 'issue #4: Test git sync [open]'",
      "d updateIssue --app taskManager --issueNumber 4 --status in_progress",
      "git log -1 — show commit: 'issue #4: Test git sync [in_progress]'",
      "d deleteIssue --app taskManager --issueNumber 4",
      "git log -1 — show commit: 'issue #4: deleted - Test git sync'",
      "Show: leader-only MySQL storage, workers forward, static git mutex",
    ],
    postState: [
      "Test issue #4 deleted",
      "Git log shows create/update/delete commits",
    ],
    enabled: false,
  },
  {
    id: 17,
    title: "App Lifecycle Management",
    features: ["Start/stop/restart", "Port registry", "Version tracking"],
    preState: [
      "taskManager and weatherApp running (from Clip 1)",
      "Terminal on right, dashboard on left showing Apps view",
    ],
    recordingSteps: [
      "Terminal: d listApps — show all registered apps",
      "d appStatus --app taskManager — show dev + prod service status",
      "d listPorts — show full port registry",
      "d stopApp --app taskManager — stop the app",
      "d appStatus --app taskManager — show stopped",
      "d startApp --app taskManager — start again",
      "d appStatus --app taskManager — show running",
      "Show dashboard Apps view updating to reflect status changes",
      "d getAppPeers --app taskManager — show per-peer version info",
      "Show port allocation: dev/prod ports for each app",
      "Mention: d deployToProd, d buildApp, d prodStatus",
    ],
    postState: [
      "taskManager running",
      "Dashboard Apps view showing all app statuses",
    ],
    enabled: false,
  },
  {
    id: 18,
    title: "Skills System Overview",
    features: ["/fix-issues-skill", "/close-issue-skill", "Commit format", "Issue lifecycle"],
    preState: [
      "Issues exist, terminal on right, dashboard on left",
    ],
    recordingSteps: [
      "Show /fix-issues-skill being invoked in terminal",
      "Skill gathers open issues — picks one — marks in_progress",
      "Claude implements fix — commits with '#N: title' format — pushes",
      "Skill marks issue as review with insights",
      "Show /close-issue-skill — matches work to issue, closes with insights",
      "Show resume button appearing after close",
      "Briefly mention other skills: desktop-automation, android-deploy, kill-process, agent-team",
    ],
    postState: [
      "One issue moved to review via skill workflow",
      "Commit pushed with issue reference",
    ],
    enabled: false,
  },
  {
    id: 19,
    title: "Terminal Wrapper & Helpers",
    features: ["claude wrapper", "Session ID", "Resume helpers", "Settings sync"],
    preState: [
      "Terminal on right monitor",
      "No special state needed",
    ],
    recordingSteps: [
      "Terminal: type claude — show it's a function",
      "Run claude — show UUID generation, CLAUDE_SESSION_ID export, session registration",
      "Show terminal title set for window tracking",
      "Exit session",
      "claudeCatResume — show available resume sessions",
      "claudePlan — browse recent plans from ~/.claude/plans/",
      "claudeLimitReset — show API limit reset calculation",
      "claudeSettingsExport — show settings sync to repo",
    ],
    postState: [
      "Terminal showing helper function outputs",
    ],
    enabled: false,
  },
  {
    id: 20,
    title: "Final Merge",
    features: ["FFmpeg merge", "All 19 clips", "Final output"],
    preState: [
      "All 19 clip videos recorded",
    ],
    recordingSteps: [
      "Concatenate all 19 clips into single video with ffmpeg",
    ],
    postState: [
      "Final merged video file",
    ],
    enabled: false,
  },
];

export function getClip(id: number): ClipDefinition | undefined {
  return clips.find(c => c.id === id);
}
